{
 "title": "Devops Dashboard 2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Status Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m]))"
    }
   ]
  },
  {
   "title": "Request Duration p95",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_bucket[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"app\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}