---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install essential packages
  apt:
    name: "{{ common_packages }}"
    state: present
  become: yes

- name: Set timezone
  timezone:
    name: "{{ common_timezone }}"
  become: yes
  when: common_timezone is defined
  notify: 
    - Restart cron  # Опционально, если хотите рестартить cron после смены таймзоны