apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-app.fullname" . }}-config
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
data:
  app.properties: |
    environment={{ .Values.environment | default "dev" }}
    log_level=info
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4 }}