---
- name: Docker role tasks
  block:
    - name: Docker installation block
      block:
        - name: Include Docker installation tasks
          include_tasks: install.yml
      rescue:
        - name: Wait 10 seconds before retry
          wait_for:
            timeout: 10
        - name: Retry Docker installation
          include_tasks: install.yml
      tags: docker_install
      become: yes

    - name: Docker configuration block
      block:
        - name: Include Docker configuration tasks
          include_tasks: config.yml
      tags: docker_config
      become: yes

  always:
    - name: Ensure Docker service is enabled and started
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes
      ignore_errors: yes   # in case Docker is not installed

  tags: docker